### ISSUE TITLE
Please share UI template and Script?

### ISSUE THREAD

**Issue by ankushgoyal27** [sjhoeksma/cordova-plugin-keychain-touch-id#1]
Hi,

Its a very nice tutorial. If possible, please share the HTML templates and script file.

Thanks.

Ankush

**Comment by sjhoeksma** [comment]
Hi,
I did not create a full working example and the project where I use it myself is private. But the readme should give you enough to start and perhaps the pointers will help.

You can only check cordova function when the document is fully loaded. When using for example the ionic framework this can be done by creating a function

```
$ionicPlatform.ready(function () {
  if (window.plugins) {
    window.plugins.touchid.isAvailable(function(){
      window.plugins.touchid.has("MyKey",function(){
         window.plugins.touchid.verify("MyKey","My Message",function(password){
             alert("Tocuh " + password);
	 });
       },function(){
	 alert("Touch ID available but no Password Key available");
    },function(msg){
	alert("no Touch ID available");
  })}
}
```
